jobs:

# Mac
########################################################################################
- job:
  displayName: 'Mac'

  pool:
    vmImage: 'macOS-10.13'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'

  steps:

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  # Get the Fatiando CI scripts (replace "master" with the version you want to use)
  - bash: git clone --branch=master --depth=1 https://github.com/fatiando/continuous-integration.git
    displayName: Fetch the Fatiando CI scripts

  # Setup dependencies and build a conda environment
  # Need to source the script to set the PATH variable globaly
  # We'll use the local version but you should use the line below instead
  #- bash: source continuous-integration/azure/setup-miniconda.sh
  #- bash: source azure/setup-miniconda.sh
    #displayName: Setup Miniconda

  # Show installed pkg information for postmortem diagnostic
  - bash: conda list
    displayName: List installed packages

  #- task: PublishTestResults@2
    #inputs:
      #testResultsFiles: 'junit/*.xml'
      #testRunTitle: 'Python $(python.version)'
    #condition: succeededOrFailed()


# Windows
########################################################################################
- job:
  displayName: 'Windows'

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python36:
        python.version: '3.6'

  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  # Get the Fatiando CI scripts (replace "master" with the version you want to use)
  - script: git clone --branch=master --depth=1 https://github.com/fatiando/continuous-integration.git
    displayName: Fetch the Fatiando CI scripts

  # Show installed pkg information for postmortem diagnostic
  - script: conda list
    displayName: List installed packages

  #- task: PublishTestResults@2
    #inputs:
      #testResultsFiles: 'junit/*.xml'
      #testRunTitle: 'Python $(python.version)'
    #condition: succeededOrFailed()
