jobs:
- job:
  displayName: 'macOS-10.13'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment python=$PYTHON_VERSION numpy pytest
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pytest --junitxml=junit/unit-test.xml
    displayName: pytest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/*.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()