jobs:
- job:
  displayName: 'vs2017-win2016'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name myEnvironment python=%PYTHON_VERSION% numpy pytest
    displayName: Create Anaconda environment

  - script: |
      activate myEnvironment
      pytest --junitxml=junit/unit-test.xml
    displayName: pytest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/*.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()